// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTB2ClM1WL5NSvixP20UY_I4YJDRGjsCE',
    appId: '1:338602720912:web:90a759d9b45ea4cbe9a215',
    messagingSenderId: '338602720912',
    projectId: 'ims-app-8e988',
    authDomain: 'ims-app-8e988.firebaseapp.com',
    storageBucket: 'ims-app-8e988.firebasestorage.app',
    measurementId: 'G-DMP2CKYHQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2VT2JFtk2HwXcrjpfdL-3QAH3W27Wito',
    appId: '1:338602720912:android:cc7cd0deae58f8ffe9a215',
    messagingSenderId: '338602720912',
    projectId: 'ims-app-8e988',
    storageBucket: 'ims-app-8e988.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-MMGdU3-J2z9zPTBg7qQneLq1BJnIZHY',
    appId: '1:338602720912:ios:84404ec8f2727b89e9a215',
    messagingSenderId: '338602720912',
    projectId: 'ims-app-8e988',
    storageBucket: 'ims-app-8e988.firebasestorage.app',
    iosBundleId: 'com.ims.imsApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTB2ClM1WL5NSvixP20UY_I4YJDRGjsCE',
    appId: '1:338602720912:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '338602720912',
    projectId: 'ims-app-8e988',
    authDomain: 'ims-app-8e988.firebaseapp.com',
    storageBucket: 'ims-app-8e988.firebasestorage.app',
    iosBundleId: 'com.ims.imsApp',
  );
}
